[project]
name = "2ndexercise"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "jayogl", email = "jayoglivie813@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "lxml>=6.1.2",
    "numpy>=2.5.2",
    "pandas>=3.0.5",
    "scikit-learn>=1.9.0",
    "streamlit>=1.62.0",
]

[project.scripts]
2ndexercise = "2ndexercise:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
