[project]
name = "3rdexercise"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "jayogl", email = "jayoglivie813@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
3rdexercise = "3rdexercise:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
